## Elo

Expected score for team A:

$$
E_A = \frac{1}{1 + 10^{(R_B - R_A)/400}}
$$

Rating update:

$$
R_A^{\text{new}} = R_A + K(S_A - E_A)
$$

where:

- $R_A, R_B$ the current Elo ratings
- $S_A = 1$ for a win $0.5$ for a draw $0$ for a loss
- $K$ factor controls how quickly ratings respond to new results (needs to be chosen)
    - could use higher K for CL matches to reflect less data. eg K = 20 for domestic leagues, $K = 30$ or $40$ for CL matches
    - could use goal diff multiplier too, to separate large wins from same wins eg $G = 1$ if 0 or 1 GD, $G=1.5$ if gd is 2, G = some function of gd if greater than 3 (tbc)
    - can use higher K in early seasons for faster standardisation

In [64]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("../data/processed/football.db")

matches = pd.read_sql_query(
    "SELECT * FROM matches",
    connection
)

print(matches.head())
matches.dtypes

   match_id        date   season competition  home_team_id  away_team_id  \
0         1  2015-06-30  2015/16          CL            14           384
1         2  2015-06-30  2015/16          CL           184             8
2         3  2015-06-30  2015/16          CL           326           104
3         4  2015-07-01  2015/16          CL           106           503
4         5  2015-07-07  2015/16          CL             8           184

     home_team_name    away_team_name  home_goals  away_goals      source
0            Pyunik           Folgore           2           1  footystats
1  Lincoln Red Imps   FC Santa Coloma           0           0  footystats
2         Crusaders   Levadia Tallinn           0           0  footystats
3      B36 Torshavn    The New Saints           1           2  footystats
4   FC Santa Coloma  Lincoln Red Imps           1           2  footystats

match_id          int64
date                str
season              str
competition         str
home_team_id      int64
away_team_id      int64
home_team_name      str
away_team_name      str
home_goals        int64
away_goals        int64
source              str
dtype: object

In [63]:
# first pass of computing elos. all initialised at 1500, K = 20

team_ids = pd.unique(
    matches[["home_team_id", "away_team_id"]].values.ravel()
)

elo = {team_id: 1500 for team_id in team_ids}

K = 20

for _, match in matches.iterrows():
    S_A = 1 if match['home_goals'] > match['away_goals'] else 0.5 if match['home_goals'] == match['away_goals'] else 0
    S_B = 1 if match['home_goals'] < match['away_goals'] else 0.5 if match['home_goals'] == match['away_goals'] else 0

    current_home_rating = elo[match['home_team_id']]
    current_away_rating = elo[match['away_team_id']]

    Q_A = 10 ** (current_home_rating / 400)
    Q_B = 10 ** (current_away_rating / 400)

    expected_home_score = Q_A / (Q_A + Q_B)
    expected_away_score = Q_B / (Q_A + Q_B)

    updated_home_rating = current_home_rating + K * (S_A - expected_home_score)
    updated_away_rating = current_away_rating + K * (S_B - expected_away_score)

    elo[match['home_team_id']] = updated_home_rating
    elo[match['away_team_id']] = updated_away_rating

elo_df = pd.DataFrame(
    list(elo.items()),
    columns=["team_id", "elo"]
)

teams = pd.read_sql_query(
    "SELECT team_id, canonical_name FROM teams",
    connection
)

elo_df = elo_df.merge(
    teams,
    on='team_id',
    how='left'
)

elo_df = elo_df.sort_values('elo', ascending=False)

top_20 = elo_df.head(20)

mid_start = len(elo_df) // 2 - 10
mid_20 = elo_df.iloc[mid_start:mid_start + 20]

bottom_20 = elo_df.tail(20)

display(top_20)
display(mid_20)
display(bottom_20)

     team_id          elo        canonical_name
133      156  1898.222312         Bayern Munich
106       70  1855.853015               Arsenal
78       140  1826.271747   Paris Saint-Germain
231      421  1824.195152             Barcelona
152      359  1799.981550                 Porto
136      363  1799.973935           Sporting CP
237      440  1798.621510           Real Madrid
220      240  1789.043630           Inter Milan
164      343  1781.796897               Benfica
124      310  1779.705496         PSV Eindhoven
60       474  1777.069447            Fenerbahce
122       87  1771.382601       Manchester City
157      475  1768.348953           Galatasaray
208      200  1763.056220            Olympiakos
190      185  1758.978107            AEK Athens
39        31  1754.814903           Club Brugge
414       47  1742.728505  Union Saint-Gilloise
142      158  1728.696008     Borussia Dortmund
210      201  1728.015785                  PAOK
27       390  1721.168183                Celtic

     team_id          elo           canonical_name
249      113  1490.699658            SJK Seinajoki
461      408  1490.683694         TSC Backa Topola
387      449  1490.522091               Djurgarden
485      466  1490.245146               Bodrumspor
472      274  1490.165386                Panevezys
388      281  1490.018860                 Floriana
394       56  1490.016550        Lokomotiva Zagreb
478      261  1490.000000                 Ordabasy
22       291  1490.000000           Rudar Pljevlja
32       273  1490.000000                Ventspils
496      393  1489.780686                  Falkirk
455      280  1489.538287         Swift Hesperange
380      386  1489.496117                Tre Fiori
356       13  1489.441539             Avan Academy
0         14  1489.288832                   Pyunik
491       12  1489.215710                  Artsakh
446        7  1488.998375  Atletic Club d'Escaldes
474      289  1488.901563                    Decic
464      126  1488.854066                 Le Havre
401      426  1488.399839                    Elche

     team_id          elo     canonical_name
105      306  1369.170694    Heracles Almelo
145      167  1368.782822        Hannover 96
276      352  1364.329396           Feirense
367       93  1360.999983   Sheffield United
381       28  1360.175358          Beerschot
283      248  1358.876268            Pescara
144      160  1358.782196       Darmstadt 98
321      251  1358.215346               SPAL
266       33  1357.511345              Eupen
191      208  1356.459737          Platanias
318      496  1354.215372   Yeni Malatyaspor
314       80  1349.503376  Huddersfield Town
109       94  1348.834839        Southampton
89        91  1346.579441       Norwich City
413       44  1345.613995            Seraing
347      443  1343.779600    Real Valladolid
132      297  1343.488586            Cambuur
311      347  1343.266854    Desportivo Aves
336      399  1336.303249         Livingston
286      484  1332.191806        Karabukspor

From the first pass ($K = 20$, inital = 1500), we can see that:

1. Roughly speaking, "better" teams are higher, and "worse" teams are lower
2. The ordering is by no means conclusive, in fact there are several strong teams that are far lower than we'd expect and vice versa (eg Fenerbahce v high, Liverpool v low)

Why?

1. There is no separation between domestic games and CL games. Hence the inter league standardisation is off. Hence we don't know if dominating Portugese leagues is equivalent to dominating English leagues.

How to fix?

1. Consider starting ELOs differing based on the performance of each league represented in the CL
2. Consider K weighting stronger for CL games

Next: See CL elos to identify how things look in that table.

In [65]:
cl_elo = {}

K = 20

for _, match in matches[matches["competition"] == "CL"].iterrows():

    if match["home_team_id"] not in cl_elo:
        cl_elo[match["home_team_id"]] = 1500

    if match["away_team_id"] not in cl_elo:
        cl_elo[match["away_team_id"]] = 1500

    S_A = 1 if match["home_goals"] > match["away_goals"] else 0.5 if match["home_goals"] == match["away_goals"] else 0
    S_B = 1 if match["home_goals"] < match["away_goals"] else 0.5 if match["home_goals"] == match["away_goals"] else 0

    current_home_rating = cl_elo[match["home_team_id"]]
    current_away_rating = cl_elo[match["away_team_id"]]

    Q_A = 10 ** (current_home_rating / 400)
    Q_B = 10 ** (current_away_rating / 400)

    expected_home_score = Q_A / (Q_A + Q_B)
    expected_away_score = Q_B / (Q_A + Q_B)

    updated_home_rating = current_home_rating + K * (S_A - expected_home_score)
    updated_away_rating = current_away_rating + K * (S_B - expected_away_score)

    cl_elo[match["home_team_id"]] = updated_home_rating
    cl_elo[match["away_team_id"]] = updated_away_rating

cl_elo_df = pd.DataFrame(
    list(cl_elo.items()),
    columns=["team_id", "elo"]
)

teams = pd.read_sql_query(
    "SELECT DISTINCT t.team_id, t.canonical_name, a.league FROM teams AS t JOIN team_aliases AS a ON t.team_id = a.team_id WHERE a.source = 'football_data'",
    connection
)

cl_elo_df = cl_elo_df.merge(
    teams,
    on="team_id",
    how="left"
)

cl_elo_df = cl_elo_df.sort_values("elo", ascending=False)

cl_elo_df.head(20)

     team_id          elo       canonical_name league
72       156  1762.763540        Bayern Munich     D1
62       440  1715.777908          Real Madrid    SP1
58       140  1713.458863  Paris Saint-Germain     F1
69        70  1682.200287              Arsenal     E0
56        87  1681.792475      Manchester City     E0
129       85  1674.385099            Liverpool     E0
74       421  1669.300790            Barcelona    SP1
145      240  1636.558272          Inter Milan     I1
70        76  1633.508785              Chelsea     E0
66       420  1610.155083      Atletico Madrid    SP1
108      158  1602.156586    Borussia Dortmund     D1
57       241  1598.169120             Juventus     I1
107       97  1581.147542    Tottenham Hotspur     E0
77       359  1569.744296                Porto     P1
105      245  1566.533501               Napoli     I1
94        68  1561.831573                  NaN    NaN
25        55  1560.109497                  NaN    NaN
61       343  1558.785814              Benfica     P1
86       335  1557.371774                  NaN    NaN
237       71  1556.998863          Aston Villa     E0

CL data shows a more "reasonable" ranking. Hence it makes sense to use this data with a higher K (to be investigated). We can also see we don't have that many - only ~2000. Hence the weak Elo separation. As an investigation, let's use this to find out the average Elo of each league.

In [67]:
cl_elo_df.groupby("league")["elo"].mean().sort_values(ascending=False)

league
E0     1598.737133
I1     1549.132860
SP1    1546.349031
P1     1544.543375
D1     1530.460034
F1     1515.282855
N1     1508.691089
G1     1484.612087
B1     1482.128009
T1     1474.693352
SC0    1469.401079
Name: elo, dtype: float64

In [ ]:
# testing different K values for CL matchups, (30, 40, 50)

team_ids = pd.unique(
    matches[["home_team_id", "away_team_id"]].values.ravel()
)

elo_results = {}

for test_k in [30, 40, 50]:

    elo = {team_id: 1500 for team_id in team_ids}

    for _, match in matches.iterrows():

        K = test_k if match["competition"] == "CL" else 20

        S_A = 1 if match["home_goals"] > match["away_goals"] else 0.5 if match["home_goals"] == match["away_goals"] else 0
        S_B = 1 if match["home_goals"] < match["away_goals"] else 0.5 if match["home_goals"] == match["away_goals"] else 0

        current_home_rating = elo[match["home_team_id"]]
        current_away_rating = elo[match["away_team_id"]]

        Q_A = 10 ** (current_home_rating / 400)
        Q_B = 10 ** (current_away_rating / 400)

        expected_home_score = Q_A / (Q_A + Q_B)
        expected_away_score = Q_B / (Q_A + Q_B)

        elo[match["home_team_id"]] = current_home_rating + K * (S_A - expected_home_score)
        elo[match["away_team_id"]] = current_away_rating + K * (S_B - expected_away_score)

    elo_df = pd.DataFrame(
        list(elo.items()),
        columns=["team_id", "elo"]
    )

    elo_df = elo_df.merge(
        teams,
        on="team_id",
        how="left"
    )

    elo_df = elo_df.sort_values("elo", ascending=False)

    elo_results[test_k] = elo_df

display(elo_results[30].head(20))
display(elo_results[40].head(20))
display(elo_results[50].head(20))

     team_id          elo        canonical_name league
133      156  1923.729137         Bayern Munich     D1
106       70  1886.941748               Arsenal     E0
78       140  1856.396663   Paris Saint-Germain     F1
231      421  1837.056033             Barcelona    SP1
237      440  1811.604052           Real Madrid    SP1
152      359  1795.492998                 Porto     P1
136      363  1794.074779           Sporting CP     P1
220      240  1787.964820           Inter Milan     I1
122       87  1778.070375       Manchester City     E0
164      343  1768.954627               Benfica     P1
124      310  1768.343225         PSV Eindhoven     N1
60       474  1767.478852            Fenerbahce     T1
39        31  1753.332479           Club Brugge     B1
208      200  1750.825314            Olympiakos     G1
157      475  1750.334582           Galatasaray     T1
190      185  1749.597077            AEK Athens     G1
414       47  1736.066863  Union Saint-Gilloise     B1
142      158  1734.876556     Borussia Dortmund     D1
111       85  1724.691821             Liverpool     E0
140      155  1722.284574      Bayer Leverkusen     D1

     team_id          elo        canonical_name league
133      156  1945.876666         Bayern Munich     D1
106       70  1913.512928               Arsenal     E0
78       140  1886.314908   Paris Saint-Germain     F1
231      421  1849.067471             Barcelona    SP1
237      440  1822.482346           Real Madrid    SP1
136      363  1795.604086           Sporting CP     P1
152      359  1793.006516                 Porto     P1
220      240  1786.663632           Inter Milan     I1
122       87  1782.876180       Manchester City     E0
124      310  1760.632274         PSV Eindhoven     N1
164      343  1760.163981               Benfica     P1
60       474  1759.554822            Fenerbahce     T1
39        31  1753.198425           Club Brugge     B1
208      200  1742.539619            Olympiakos     G1
190      185  1741.555465            AEK Athens     G1
157      475  1738.129834           Galatasaray     T1
142      158  1738.090465     Borussia Dortmund     D1
111       85  1736.636729             Liverpool     E0
140      155  1732.946276      Bayer Leverkusen     D1
414       47  1732.135842  Union Saint-Gilloise     B1

     team_id          elo       canonical_name league
133      156  1965.881098        Bayern Munich     D1
106       70  1937.052027              Arsenal     E0
78       140  1915.160936  Paris Saint-Germain     F1
231      421  1860.510538            Barcelona    SP1
237      440  1832.152648          Real Madrid    SP1
136      363  1802.397139          Sporting CP     P1
152      359  1791.853630                Porto     P1
122       87  1786.389810      Manchester City     E0
220      240  1785.136602          Inter Milan     I1
124      310  1755.391134        PSV Eindhoven     N1
39        31  1753.886329          Club Brugge     B1
164      343  1753.882193              Benfica     P1
60       474  1753.129080           Fenerbahce     T1
111       85  1746.323617            Liverpool     E0
140      155  1742.681447     Bayer Leverkusen     D1
222      241  1739.878150             Juventus     I1
142      158  1739.222655    Borussia Dortmund     D1
208      200  1737.252526           Olympiakos     G1
80        71  1736.829699          Aston Villa     E0
190      185  1734.570408           AEK Athens     G1

We can now see that the top leagues are rising to the top more consistently, but we're still overrepresented by etams which are stronger in their leagues, but not necessarily on a global stage. Although important not to overfit to "perception", there are some clear issues in this listing. As such. we should implement different starting Elos per league. We must ask the question of how to choose such values fairly.

We need to choose which K is best, and then following that find a better way to interrelate the leagues.

One idea is:
Take an external elo source from start of/pre 2015/2016, and calculate the average elo for each league. We can then scale it and reaverage around 1500: ie


R_league = 1500 + (league Elo - league average)

We cannot use current or future values to initialise elo, so this seems a clean way of doing so, importing only one value per team.

It then makes sense to recompute the multiple K's after this, and find a metric to choose the optimal K for CL games.

We will now get data values from ClubElo

In [ ]:
import soccerdata as sd

clubelo = sd.ClubElo()

elo_2015 = clubelo.read_by_date("2015-06-30")

elo_2015.head()

[08/13/26 15:13:26] INFO     Saving cached data to C:\Users\rohan\soccerdata\data\ClubElo            ]8;id=5782913;file://c:\Users\rohan\Documents\UCL-MU-Predictor\.venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=5782914;file://c:\Users\rohan\Documents\UCL-MU-Predictor\.venv\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

,rank,country,level,elo,from,to,league
team,,,,,,,
Barcelona,1.0,ESP,1,2087.628174,2015-06-07,2015-07-30,ESP-La Liga
Real Madrid,2.0,ESP,1,2062.575928,2015-06-07,2015-07-30,ESP-La Liga
Bayern,3.0,GER,1,1980.296631,2015-05-24,2015-07-30,GER-Bundesliga
Atletico,4.0,ESP,1,1945.396240,2015-06-07,2015-07-30,ESP-La Liga
Juventus,5.0,ITA,1,1932.656616,2015-06-07,2015-07-30,ITA-Serie A

In [77]:
countries = [
    "ENG",
    "SCO",
    "GER",
    "ESP",
    "ITA",
    "FRA",
    "BEL",
    "NED",
    "POR",
    "TUR",
    "GRE"
]

top_leagues = elo_2015[
    (elo_2015["country"].isin(countries)) &
    (elo_2015["level"] == 1)
]

league_elos = (
    top_leagues
    .groupby("country")["elo"]
    .mean()
    .sort_values(ascending=False)
)

league_elos

country
ESP    1766.790265
GER    1704.133748
ENG    1691.311475
ITA    1661.208600
FRA    1607.575476
POR    1518.692322
TUR    1506.674601
BEL    1443.854294
NED    1440.908542
GRE    1387.999410
SCO    1296.675364
Name: elo, dtype: float64

Using this data, we'll recompute the Elo ratings, with starting values as shown.

In [ ]:
# third pass of computing elos. initialised according to ClubElo data, K = 20 fixed

# conversion dict for league to elo avg
league_to_country = {
    "E0": "ENG",
    "SC0": "SCO",
    "D1": "GER",
    "SP1": "ESP",
    "I1": "ITA",
    "F1": "FRA",
    "B1": "BEL",
    "N1": "NED",
    "P1": "POR",
    "T1": "TUR",
    "G1": "GRE"
}

team_leagues = pd.read_sql_query(
    "SELECT DISTINCT team_id, league FROM team_aliases WHERE source = 'football_data'",
    connection
)

initialised_elo = {}

for _, team in team_leagues.iterrows():

    league = team["league"]
    country = league_to_country[league]

    starting_rating = league_elos.loc[country]

    initialised_elo[team["team_id"]] = starting_rating


K = 20

for _, match in matches.iterrows():

    # for teams outside our 11 domestic leagues
    if match["home_team_id"] not in initialised_elo:
        initialised_elo[match["home_team_id"]] = 1500

    if match["away_team_id"] not in initialised_elo:
        initialised_elo[match["away_team_id"]] = 1500

    S_A = 1 if match["home_goals"] > match["away_goals"] else 0.5 if match["home_goals"] == match["away_goals"] else 0
    S_B = 1 if match["home_goals"] < match["away_goals"] else 0.5 if match["home_goals"] == match["away_goals"] else 0

    current_home_rating = initialised_elo[match["home_team_id"]]
    current_away_rating = initialised_elo[match["away_team_id"]]

    Q_A = 10 ** (current_home_rating / 400)
    Q_B = 10 ** (current_away_rating / 400)

    expected_home_score = Q_A / (Q_A + Q_B)
    expected_away_score = Q_B / (Q_A + Q_B)

    updated_home_rating = current_home_rating + K * (S_A - expected_home_score)
    updated_away_rating = current_away_rating + K * (S_B - expected_away_score)

    initialised_elo[match["home_team_id"]] = updated_home_rating
    initialised_elo[match["away_team_id"]] = updated_away_rating

initialised_elo_df = pd.DataFrame(
    list(initialised_elo.items()),
    columns=["team_id", "elo"]
)

teams = pd.read_sql_query(
    "SELECT team_id, canonical_name FROM teams",
    connection
)

initialised_elo_df = initialised_elo_df.merge(
    teams,
    on="team_id",
    how="left"
)

initialised_elo_df = initialised_elo_df.sort_values("elo", ascending=False)

top_20 = initialised_elo_df.head(20)

top_20

     team_id          elo       canonical_name
93       156  2050.360927        Bayern Munich
262      421  2018.523373            Barcelona
25        70  2008.559136              Arsenal
281      440  1989.862114          Real Madrid
83       140  1953.110627  Paris Saint-Germain
42        87  1933.987410      Manchester City
163      240  1929.515784          Inter Milan
95       158  1893.968345    Borussia Dortmund
261      420  1878.984622      Atletico Madrid
92       155  1865.260673     Bayer Leverkusen
40        85  1862.694515            Liverpool
235      363  1857.028291          Sporting CP
280      439  1856.101058           Real Betis
43        88  1854.911807    Manchester United
26        71  1850.606665          Aston Villa
173      250  1848.464619                 Roma
168      245  1848.078053               Napoli
164      241  1846.699370             Juventus
215      343  1845.717284              Benfica
288      447  1842.066840           Villarreal

On inspection this is much more effective than our idea of choosing a valid K. Unsurprising given the (somewhat) small dataset, that priors would make a large impact. We should not neglect the increase K measure for CL matches,a s it appeared to optimise our Elo ratings in a positive dimension.

We need a metric by which to choose our best K for CL values. We could use mean square error of the $S$ value and $E$ value (the average difference between the observed result and the expected result from the elo):

$$
\text{MSE} = \frac{1}{n} \sum{(S_{A} - E_{A})^{2}} 
$$

In [ ]:
matches = matches.sort_values("date").reset_index(drop=True)

mse_results = {}

for test_k in [20, 30, 40, 50]:

    initialised_elo = {}

    for _, team in team_leagues.iterrows():

        league = team["league"]
        country = league_to_country[league]
        starting_rating = league_elos.loc[country]

        initialised_elo[team["team_id"]] = starting_rating

    validation_errors = []

    for _, match in matches.iterrows():

        if match["home_team_id"] not in initialised_elo:
            initialised_elo[match["home_team_id"]] = 1500

        if match["away_team_id"] not in initialised_elo:
            initialised_elo[match["away_team_id"]] = 1500

        if match["competition"] == "CL":
            K = test_k
        else:
            K = 20

        if match["home_goals"] > match["away_goals"]:
            S_A = 1
            S_B = 0

        elif match["home_goals"] == match["away_goals"]:
            S_A = 0.5
            S_B = 0.5

        else:
            S_A = 0
            S_B = 1

        current_home_rating = initialised_elo[match["home_team_id"]]
        current_away_rating = initialised_elo[match["away_team_id"]]

        Q_A = 10 ** (current_home_rating / 400)
        Q_B = 10 ** (current_away_rating / 400)

        expected_home_score = Q_A / (Q_A + Q_B)
        expected_away_score = Q_B / (Q_A + Q_B)

        if match["season"] == "2023/24" and match["competition"] == "CL":
            squared_error = (S_A - expected_home_score) ** 2
            validation_errors.append(squared_error)

        updated_home_rating = current_home_rating + K * (S_A - expected_home_score)
        updated_away_rating = current_away_rating + K * (S_B - expected_away_score)

        initialised_elo[match["home_team_id"]] = updated_home_rating
        initialised_elo[match["away_team_id"]] = updated_away_rating

    mse = sum(validation_errors) / len(validation_errors)

    mse_results[test_k] = mse

for k, mse in mse_results.items():
    print(k, mse)

20 0.1453701493706558
30 0.14479113535327903
40 0.14499139734431643
50 0.14559589932275005

We can see that all the MSE's are of negligible difference, hence we proceed witha universial $K = 20$ for simplicity.

We have now generated our calculated for our Elo table. For completeness, the cell below will contain the final Elo table calculation, with a full print of the Elos.

In [85]:
# final Elo calculation: ClubElo league starting values, K = 20

matches = matches.sort_values("date").reset_index(drop=True)

league_to_country = {
    "E0": "ENG",
    "SC0": "SCO",
    "D1": "GER",
    "SP1": "ESP",
    "I1": "ITA",
    "F1": "FRA",
    "B1": "BEL",
    "N1": "NED",
    "P1": "POR",
    "T1": "TUR",
    "G1": "GRE"
}

team_leagues = pd.read_sql_query(
    "SELECT DISTINCT team_id, league FROM team_aliases WHERE source = 'football_data'",
    connection
)

final_elo = {}

for _, team in team_leagues.iterrows():

    league = team["league"]
    country = league_to_country[league]

    starting_rating = league_elos.loc[country]

    final_elo[team["team_id"]] = starting_rating


K = 20

for _, match in matches.iterrows():

    if match["home_team_id"] not in final_elo:
        final_elo[match["home_team_id"]] = 1500

    if match["away_team_id"] not in final_elo:
        final_elo[match["away_team_id"]] = 1500

    if match["home_goals"] > match["away_goals"]:
        S_A = 1
        S_B = 0

    elif match["home_goals"] == match["away_goals"]:
        S_A = 0.5
        S_B = 0.5

    else:
        S_A = 0
        S_B = 1

    current_home_rating = final_elo[match["home_team_id"]]
    current_away_rating = final_elo[match["away_team_id"]]

    Q_A = 10 ** (current_home_rating / 400)
    Q_B = 10 ** (current_away_rating / 400)

    expected_home_score = Q_A / (Q_A + Q_B)
    expected_away_score = Q_B / (Q_A + Q_B)

    updated_home_rating = current_home_rating + K * (S_A - expected_home_score)
    updated_away_rating = current_away_rating + K * (S_B - expected_away_score)

    final_elo[match["home_team_id"]] = updated_home_rating
    final_elo[match["away_team_id"]] = updated_away_rating


final_elo_df = pd.DataFrame(
    list(final_elo.items()),
    columns=["team_id", "elo"]
)

teams = pd.read_sql_query(
    "SELECT team_id, canonical_name FROM teams",
    connection
)

final_elo_df = final_elo_df.merge(
    teams,
    on="team_id",
    how="left"
)

final_elo_df = final_elo_df.sort_values("elo", ascending=False)

display(final_elo_df)

     team_id          elo                canonical_name
93       156  2050.360927                 Bayern Munich
262      421  2018.523373                     Barcelona
25        70  2008.559136                       Arsenal
281      440  1989.862114                   Real Madrid
83       140  1953.110627           Paris Saint-Germain
42        87  1933.987410               Manchester City
163      240  1929.515784                   Inter Milan
95       158  1893.968345             Borussia Dortmund
261      420  1878.984622               Atletico Madrid
92       155  1865.260673              Bayer Leverkusen
40        85  1862.694515                     Liverpool
235      363  1857.028291                   Sporting CP
280      439  1856.101058                    Real Betis
43        88  1854.911807             Manchester United
26        71  1850.606665                   Aston Villa
173      250  1848.464619                          Roma
168      245  1848.078053                        Napoli
164      241  1846.699370                      Juventus
215      343  1845.717284                       Benfica
288      447  1842.066840                    Villarreal
231      359  1840.911374                         Porto
113      176  1831.675603                    RB Leipzig
117      180  1830.570563                 VfB Stuttgart
27        72  1823.489890                   Bournemouth
147      224  1811.243893                      AC Milan
155      232  1807.500211                          Como
306      475  1804.374204                   Galatasaray
264      423  1800.611157                    Celta Vigo
279      438  1799.426126                Rayo Vallecano
45        90  1795.571492              Newcastle United
148      225  1793.038830                      Atalanta
29        74  1791.541562        Brighton & Hove Albion
305      474  1790.980250                    Fenerbahce
287      446  1790.325184                      Valencia
31        76  1786.282275                       Chelsea
199      310  1782.205354                 PSV Eindhoven
28        73  1781.879414                     Brentford
107      170  1778.422598                    Hoffenheim
71       128  1775.610759                         Lille
70       127  1772.227724                          Lens
165      242  1771.001294                         Lazio
260      419  1768.813662               Athletic Bilbao
101      164  1764.670576                      Freiburg
34        79  1763.412114                        Fulham
150      227  1761.547655                       Bologna
283      442  1760.789786                 Real Sociedad
269      428  1758.921118                        Getafe
47        92  1758.465931             Nottingham Forest
33        78  1751.016185                       Everton
110      173  1750.005356                      Mainz 05
32        77  1747.938214                Crystal Palace
5         31  1746.112256                   Club Brugge
258      417  1744.460047                        Alaves
73       130  1744.285311                          Lyon
275      434  1743.562750                       Levante
76       133  1742.929764                        Monaco
278      437  1737.895814                       Osasuna
159      236  1737.503823                    Fiorentina
277      436  1735.255137                      Mallorca
98       161  1732.592328           Eintracht Frankfurt
52        97  1731.838429             Tottenham Hotspur
74       131  1731.696889                     Marseille
270      429  1729.892293                        Girona
38        83  1728.758283                  Leeds United
274      433  1728.623026                       Leganes
91       154  1727.464353                      Augsburg
268      427  1726.052808                      Espanyol
285      444  1725.062238                       Sevilla
21        47  1721.343210          Union Saint-Gilloise
267      426  1717.785565                         Elche
55       100  1714.374326               West Ham United
85       142  1713.958726                        Rennes
87       144  1713.539618                    Strasbourg
51        96  1713.430344                    Sunderland
96       159  1709.692853      Borussia Monchengladbach
272      431  1708.436916                        Huesca
263      422  1701.991883                         Cadiz
234      362  1701.000020                Sporting Braga
116      179  1698.199684                  Union Berlin
135      200  1697.963596                    Olympiakos
282      441  1690.411206                   Real Oviedo
180      257  1689.907161                       Udinese
266      425  1686.593168                         Eibar
179      256  1686.488869                        Torino
118      181  1680.735430                 Werder Bremen
103      166  1678.986032                  Hamburger SV
371      499  1678.301949              Shakhtar Donetsk
325      494  1677.422437                   Trabzonspor
286      445  1675.198710                Sporting Gijon
394       68  1673.303659                 FC Copenhagen
161      238  1672.154749                         Genoa
190      301  1669.931219                     Feyenoord
170      247  1668.325246                         Parma
177      254  1666.241084                      Sassuolo
120      185  1665.651196                    AEK Athens
356       55  1663.059589                 Dinamo Zagreb
152      229  1659.891149                      Cagliari
82       139  1659.304760                      Paris FC
100      163  1659.039452            Fortuna Dusseldorf
119      182  1659.031183                     Wolfsburg
265      424  1658.391213           Deportivo La Coruna
259      418  1657.523205                       Almeria
296      465  1653.118927                      Besiktas
99       162  1652.449146                       FC Koln
88       145  1652.277722                      Toulouse
108      171  1648.246208                 Holstein Kiel
109      172  1644.750945                    Ingolstadt
313      482  1644.013733           Istanbul Basaksehir
90       153  1643.778955             Arminia Bielefeld
63       120  1643.368453                         Brest
273      432  1643.226760                    Las Palmas
166      243  1636.092008                         Lecce
136      201  1635.745493                          PAOK
105      168  1635.525876                    Heidenheim
72       129  1633.328180                       Lorient
56       101  1632.393544       Wolverhampton Wanderers
80       137  1631.345081                          Nice
373       18  1630.318949             Red Bull Salzburg
328      500  1630.217106                  Cardiff City
94       157  1629.761896                        Bochum
106      169  1627.930504                 Hertha Berlin
271      430  1626.013303                       Granada
153      230  1625.600728                         Carpi
456      329  1625.286916                    Bodo/Glimt
50        95  1625.124128                    Stoke City
276      435  1625.109348                        Malaga
222      350  1624.753635                     Famalicao
115      178  1622.901474                      St Pauli
36        81  1620.186387                     Hull City
114      177  1620.138872                    Schalke 04
184      295  1618.847329                          Ajax
60       117  1617.066424                       Auxerre
41        86  1616.418445                    Luton Town
102      165  1616.257005                Greuther Furth
329      502  1613.809136                  Swansea City
39        84  1611.769120                Leicester City
358       21  1610.374833                       Qarabag
323      492  1609.980524                    Samsunspor
37        82  1606.166504                  Ipswich Town
158      235  1600.432523                        Empoli
156      233  1599.380288                     Cremonese
112      175  1599.296619                     Paderborn
69       126  1597.563010                      Le Havre
178      255  1597.275032                        Spezia
44        89  1596.637546                 Middlesbrough
204      315  1595.812772                        Twente
54        99  1591.110821          West Bromwich Albion
84       141  1590.885558                         Reims
376      498  1590.118843                   Dynamo Kyiv
181      258  1588.667695                       Venezia
111      174  1588.048159                      Nurnberg
382      335  1584.471041                  Legia Warsaw
311      480  1583.867107                       Goztepe
30        75  1583.569003                       Burnley
138      203  1580.851722                 Panathinaikos
368      378  1579.720437                   CSKA Moscow
242      390  1578.503421                        Celtic
160      237  1578.493277                     Frosinone
284      443  1575.839576               Real Valladolid
65       122  1573.380829                 Clermont Foot
501       63  1572.215114                         Pafos
205      316  1570.046995                       Utrecht
8         34  1568.151463                          Genk
162      239  1565.111582                 Hellas Verona
370      456  1565.105711                    Young Boys
391      214  1564.518697                   Ferencvaros
59       116  1563.964849                        Angers
53        98  1563.962315                       Watford
387      407  1563.399172             Red Star Belgrade
104      167  1562.926219                   Hannover 96
238      366  1562.484616             Vitoria Guimaraes
151      228  1561.266030                       Brescia
183      294  1559.180285                    AZ Alkmaar
149      226  1558.423907                     Benevento
389      287  1557.557402              Sheriff Tiraspol
375      383  1556.711856           Zenit St Petersburg
197      308  1554.441967                  NEC Nijmegen
461      222  1553.800468                 Maccabi Haifa
19        45  1552.778722                  Sint-Truiden
81       138  1552.065051                         Nimes
172      249  1550.084414                          Pisa
86       143  1549.432065                 Saint-Etienne
97       160  1548.844106                  Darmstadt 98
438      379  1548.607578                     Krasnodar
67       124  1548.573586               Gazelec Ajaccio
175      252  1548.402729                   Salernitana
176      253  1547.649627                     Sampdoria
352      451  1547.409906                      Malmo FF
167      244  1547.407251                         Monza
213      341  1547.392601                        Arouca
478      337  1544.369268             Rakow Czestochowa
361       59  1544.312101                 APOEL Nicosia
299      468  1544.136287               Caykur Rizespor
388      221  1543.556366             Hapoel Beer Sheva
169      246  1543.544797                       Palermo
79       136  1543.340298                        Nantes
58       115  1542.762341                        Amiens
364       69  1541.760991                   Midtjylland
398      381  1541.431076                        Rostov
414       64  1541.253175                 Slavia Prague
225      353  1541.218288                   Gil Vicente
61       118  1541.021693                        Bastia
367       66  1540.720748                Viktoria Plzen
62       119  1540.203308                      Bordeaux
369       65  1538.739066                 Sparta Prague
48        93  1538.540736              Sheffield United
354       22  1536.090228                  BATE Borisov
78       135  1536.045127                         Nancy
319      488  1535.958722                     Konyaspor
154      231  1535.698161                 Chievo Verona
157      234  1534.430474                       Crotone
366       54  1533.908189            Ludogorets Razgrad
35        80  1533.113234             Huddersfield Town
392      332  1532.461281                     Rosenborg
374      453  1532.358067                         Basel
292      461  1531.501530                    Alanyaspor
316      485  1531.451618                     Kasimpasa
233      361  1530.653057                   Santa Clara
227      355  1528.629687                    Moreirense
0         26  1527.551387                    Anderlecht
46        91  1527.150390                  Norwich City
436      409  1526.324096             Slovan Bratislava
49        94  1523.931670                   Southampton
220      348  1523.898824                       Estoril
212      340  1521.702356                       Alverca
68       125  1521.413763                      Guingamp
451      108  1521.401359                   KI Klaksvik
348      414  1521.346763                       Maribor
171      248  1519.849647                       Pescara
482      450  1518.402952                        Hacken
174      251  1516.632382                          SPAL
340      334  1515.738309                   Lech Poznan
343      331  1515.455633                         Molde
353      276  1515.454227              Zalgiris Vilnius
425      374  1514.949328                      CFR Cluj
64       121  1514.133435                          Caen
350      213  1514.059594                      Fehervar
344      406  1512.796189             Partizan Belgrade
303      472  1511.594992                      Eyupspor
427      380  1511.318190              Lokomotiv Moscow
349      259  1510.795737                        Astana
232      360  1510.598256                       Rio Ave
57       114  1509.765065                    AC Ajaccio
457       20  1509.675065                   Neftci Baku
455      415  1509.300128                          Mura
310      479  1509.174167                   Giresunspor
442       23  1508.526609                  Dinamo Brest
122      187  1508.428776             Aris Thessaloniki
445       62  1508.088807                Omonia Nicosia
437       16  1507.710522                          LASK
428      265  1507.593906                    Feronikeli
416      382  1506.826233                Spartak Moscow
448      413  1506.760489                         Celje
194      305  1506.382696                    Heerenveen
462      260  1505.309533                 Kairat Almaty
77       134  1505.239879                   Montpellier
395      416  1505.145647            Olimpija Ljubljana
362      110  1504.750189                  HJK Helsinki
412      412  1504.061490                        Zilina
486       61  1503.766687                 Aris Limassol
430      448  1503.582037                           AIK
417      264  1503.419528                         Drita
9         35  1503.124183                          Gent
481      376  1502.856335               Farul Constanta
492       24  1502.828703                  Dinamo Minsk
496      286  1502.694223             Petrocub Hincesti
424      410  1502.594948                Spartak Trnava
471       58  1501.933760                   AEK Larnaca
484      455  1501.460816                      Servette
493        1  1501.212079            Egnatia Rrogozhine
472       60  1501.203685              Apollon Limassol
497      333  1500.692934         Jagiellonia Bialystok
467      270  1500.661624                      Rigas FS
453      266  1500.578924                     Prishtina
393      452  1500.575011                    Norrkoping
474      215  1500.296697                    Breidablik
415      377  1500.244353            Viitorul Constanta
447      112  1500.186087                          KuPS
464      220  1499.934085            Vikingur Reykjavik
338        5  1499.458728              Skenderbeu Korce
297      466  1499.343026                    Bodrumspor
475       15  1498.800043                        Urartu
418      152  1498.433157               Torpedo Kutaisi
502      330  1498.162943                         Brann
407       57  1497.649256                        Rijeka
317      486  1497.632637                   Kayserispor
318      487  1497.133130                   Kocaelispor
485      497  1496.997334                      Dnipro-1
372       17  1496.213828                    Rapid Wien
20        46  1495.768745                Standard Liege
324      493  1495.740682                     Sivasspor
254      402  1495.622529                       Rangers
360      325  1494.630498                 Vardar Skopje
498      454  1494.492998                        Lugano
470      457  1494.139080                        Zurich
347      375  1494.128025                          FCSB
465      322  1493.597934                        Shkupi
443      217  1493.150448                  KR Reykjavik
433      336  1492.696240                 Piast Gliwice
294      463  1492.518920                    Ankaragucu
469      262  1492.422405                Tobol Kostanay
439        9  1492.343298         Inter Club d'Escaldes
386      113  1492.320295                 SJK Seinajoki
403      183  1491.847743                     Europa FC
487      408  1491.758029              TSC Backa Topola
468      148  1491.613470                 Dinamo Batumi
304      473  1491.598574              Fatih Karagumruk
441      323  1491.516749                        Sileks
466      263  1491.474286                      Ballkani
500      372  1491.417507                    Shelbourne
413        3  1491.340065                        Kukesi
346      411  1491.102323                       Trencin
399      373  1491.086762                 Astra Giurgiu
396      216  1491.036194              FH Hafnarfjordur
307      476  1490.765935                  Gaziantep FK
446      449  1490.575196                    Djurgarden
488      274  1490.265329                     Panevezys
330       14  1490.009262                        Pyunik
363      273  1490.000000                     Ventspils
495      261  1490.000000                      Ordabasy
359      291  1490.000000                Rudar Pljevlja
452       56  1489.928154             Lokomotiva Zagreb
450      281  1489.860085                      Floriana
499       12  1489.695381                       Artsakh
483      280  1489.652795              Swift Hesperange
429       13  1489.441539                  Avan Academy
4         30  1489.429604                     Charleroi
440      386  1489.289927                     Tre Fiori
217      345  1489.103758                      Casa Pia
454       51  1489.067603              Borac Banja Luka
473        7  1489.007665       Atletic Club d'Escaldes
426       19  1488.984555                    Sturm Graz
490      289  1488.898415                         Decic
295      464  1487.670085                   Antalyaspor
419      321  1487.190391                     Shkendija
385      278  1486.415376                 F91 Dudelange
12        38  1486.087005                      Mechelen
463       67  1485.594783                       Brondby
431      105  1484.956062                   Nomme Kalju
420      369  1483.500192                     Cork City
459      371  1483.123204               Shamrock Rovers
409      111  1482.625023                 IFK Mariehamn
336      106  1482.231671                  B36 Torshavn
411      271  1482.179626              Spartaks Jurmala
489       10  1482.079232               UE Santa Coloma
410      212  1481.775836               Budapest Honved
432      107  1481.134474                   HB Torshavn
322      491  1480.844131                    Pendikspor
406      151  1480.632781                     Samtredia
401      267  1480.575011                     Trepca'89
345      147  1480.575011                     Dila Gori
384      268  1480.574088                       Liepaja
365      285  1480.561981                 Milsami Orhei
402      102  1480.542914                   FCI Tallinn
479      272  1480.191465                      Valmiera
397      290  1480.016549             Mladost Podgorica